### ISSUE TITLE
Hello, the following problem occurred when I tried to repeat this work. There is no free_energy.dat file in the data folder.

### ISSUE THREAD

**Issue by 747945** [freitas-rodrigo/FreeEnergyLAMMPS#3]
$ python integrate.py
Traceback (most recent call last):
  File "D:\LAMMPS\LAMMPS 64-bit 29Oct2020\FreeEnergyLAMMPS-master\frenkel_ladd\post_processing\integrate.py", line 16, in <module>
    T, F0 = loadtxt('../../frenkel_ladd/data/free_energy.dat', unpack=True)
  File "E:\python\lib\site-packages\numpy\lib\npyio.py", line 1042, in loadtxt
    fh = np.lib._datasource.open(fname, 'rt', encoding=encoding)
  File "E:\python\lib\site-packages\numpy\lib\_datasource.py", line 193, in open
    return ds.open(path, mode, encoding=encoding, newline=newline)
  File "E:\python\lib\site-packages\numpy\lib\_datasource.py", line 532, in open
    raise FileNotFoundError(f"{path} not found.")
FileNotFoundError: ../../frenkel_ladd/data/free_energy.dat not found.

**Comment by freitas-rodrigo** [comment]
LAMMPS seems to have change their directory structure. I modified the
instructions to account for that. The "cp USER-MISC/fix_ti_spring.* ."
command should now be ""cp EXTRA-FIX/fix_ti_spring.* ."
